### ISSUE TITLE
Add link to original message in /listremind

### ISSUE THREAD

**Issue by Octol1ttle** [LabsDevelopment/Octobot#200]
### Description

A popular usecase of reminders involves creating a reminder with a generic text like `this` to refer to messages sent prior to the reminder. However, in `/listremind`, it becomes hard to know what `this` actually refers to

### Proposed Solution

Add a reference link to the original message in `/listremind`, similar to `Jump to message` in message edited embed

**Comment by Apceniy** [comment]
In this case it can be added to the reminder itself as well
