### ISSUE TITLE
Reformat Octobot's code

### ISSUE THREAD

**Issue by mctaylors** [LabsDevelopment/Octobot#228]
This pull request is *filled* with unnecessary formatting changes.

_Originally posted by @Octol1ttle in https://github.com/LabsDevelopment/Octobot/pull/223#discussion_r1429614037_

newlines go brrr

**Comment by Octol1ttle** [comment]
Global reformatting PRs are not a good idea IMHO. It's better to reformat pieces of code when changing them (e.g. if I change 5 lines in a method, it's alright to fix important formatting issues in these lines and a bit around them)

I tried making a few reformatting PRs myself and realised that most changes change nothing (pun not intended) of significance and in most times they actually *hurt* readability. It's better to reformat code only manually and only when you feel "this code is hard to read and I know how to make it better"
